deployment:
  role: traditional
  admin:
    allow_admin:
      - 0.0.0.0/0
    admin_key:
      - name: "admin"
        key: edd1c9f034335f136f87ad84b625c88b
        role: admin
  etcd:
    host:
      - "http://etcd:2379"
    prefix: "/apisix"
    timeout: 30

apisix:
  node_listen: 9080
  enable_ipv6: false
  enable_control: true
  control:
    ip: "0.0.0.0"
    port: 9090

plugins:
  - pii-masker
  - prometheus
  - limit-count
  - key-auth
  - opentelemetry
  - traffic-blocker

plugin_attr:
  prometheus:
    export_addr:
      ip: "0.0.0.0"
      port: 9091
  opentelemetry:
    resource:
      service.name: "apisix-gateway"
      instance.id: "\$hostname"
    collector:
      address: "jaeger:4317"
      request_timeout: 3
